### ISSUE TITLE
Trying to install in SvelteKit

### ISSUE THREAD

**Issue by Antc1993** [project-nv/night-vision#83]
### Describe the bug

Hello, I am trying to install NightVision in SvelteKit but it always gives me the same error
500
Worker is not defined

ReferenceError: Worker is not defined
    at WebWork.start (/node_modules/night-vision/dist/index-d313a23d.js:4779:23)
    at new WebWork (/node_modules/night-vision/dist/index-d313a23d.js:4772:10)
    at Object.instance$e [as instance] (/node_modules/night-vision/dist/index-d313a23d.js:4840:23)
    at new NightVision2 (/node_modules/night-vision/dist/index-d313a23d.js:11078:25)
    at index.svelte:9:16
    at Object.$$render (/sandbox/node_modules/svelte/internal/index.js:1380:22)
    at Object.default (root.svelte:38:46)
    at /sandbox/.svelte-kit/dev/components/layout.svelte:5:41
    at Object.$$render (/sandbox/node_modules/svelte/internal/index.js:1380:22)
    at root.svelte:36:44
Any ideas ? thank you.

### Reproduction

https://codesandbox.io/s/bold-moser-82qsx2?file=/src/routes/index.svelte

### Javascript Framework

svelte

### Validations

- [X] Read the [docs](https://nightvision.dev/guide/intro/getting-started.html).
- [X] Check that there isn't [already an issue](https://github.com/project-nv/night-vision/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a NightVision issue and not a framework-specific issue.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Antc1993** [comment]
Hello, I was able to solve it this way

    ```
     import {onMount} from  'svelte';

    onMount(async () =>{
        const NightVision =  await import('night-vision');
        function data() {
            return Array(30).fill(1).map((x, i) => [
                new Date(`${i+1} Nov 2022 GMT+0000`).getTime(),
                i * Math.random()
            ])
        }
        let chart = new NightVision.NightVision('chart-container')
        chart.data = {
            panes: [{
                overlays: [{
                    name: 'APE Stock',
                    type: 'Spline',
                    data: data(),
                    settings: {
                        precision: 2
                    }
                }]
            }]
        }

    });
```
Thanks
